### ISSUE TITLE
Remove the necessity for sudo

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker#48]
As `npm` in combination with `sudo` causes lots of problems, especially when native modules are involved, we should look into ways to remove that necessity. This issue is supposed to be a collection of code snippets and thoughts to reach that goal.

## 1. Take ownership of `/opt/iobroker` instead of `chmod 777`
```bash
sudo chown $(whoami) -R /opt/iobroker
```
### Upsides:
* ioBroker can be installed without `sudo` or `--unsafe-perm`.  
* ioBroker can be executed without sudo.
* Installation of adapters which compile native modules works without `sudo` and `--unsafe-perm`. No more `gyp` [loop of death](https://github.com/sass/node-sass/issues/2006)
### Downsides:
* Automatic registration as a system service does not work.  
  This could potentially be solved by #47 or a new command `iobroker startup` which the user has to run with `sudo` that does the necessary system stuff.
* `iobroker <command>` does not work. `./iobroker` has to be used. This could also be solved by the aforementioned command.

## 2. What to do with adapter that need system access?
I'm still unclear about this. Maybe single adapter can be run with root rights. Preferably there's some other way.
### `serialport` requires root to access serial ports
Under Linux the user has to be added to the `dialout` group:
```bash
sudo usermod -a -G dialout $(whoami)
```
Afterwards the user has to logout and login again (*can this be done from script?*), or just `reboot`.

Under Windows I had no issues accessing the serial port from a non-admin console.

### `zwave` requires system access to build OZW during the installation.
TODO

### Linux
```js
// elevated rights
process.getuid() // returns 0 when sudo/root, something else otherwise

// sudo OR sudo su
process.env.USER === "root"
process.env.SUDO_USER != undefined // contains the non-root user

// real root (su)
process.env.USER === "root"
process.env.SUDO_USER === undefined
```
### Windows
`node-windows` has the method `isAdminUser()` to check for admin rights

### Linux
On the command line, just `execSync("sudo <command>")`. The sudo question will show up.
From within a script/admin GUI, we can `execSync("echo <password> | sudo -S <command>")`.

### Windows
`node-windows` has the method `elevate`. But is this even necessary?

----

## TODOs / open questions:
- [x] How to automatically start ioBroker?
- [x] How to use `iobroker <command>` over `./iobroker <command>`?
- [x] How to make `serialport` work?
- [x] How to make `zwave` work?
- [ ] How to re-login the user from a script (after adding him to the dialout group)?

**Comment by GermanBluefox** [comment]
We have 3 known problems with sudo:
- serial COM
- ping
- port 80 (e.g. for letssncrypt)
Solutions: 
## 1
sudo usermod -a -G dialout $USER
sudo usermod -a -G tty $USER

## 2 
https://superuser.com/questions/1003912/ping-doesnt-work-on-non-root-user

## 3 
setcap 'cap_net_bind_service=+ep' /usr/bin/node

**Comment by AlCalzone** [comment]
Not sure I understand. How would we use that flag?

**Comment by GermanBluefox** [comment]
The Problem is only if the user installs something from console with
different user. If everything is executed from admin, so the rights are
always valid.

This flag disables chmod after installation or update

пт, 8 июн. 2018 г., 11:07 AlCalzone <notifications@github.com>:

**Comment by Apollon77** [comment]
Do you committed the "use" of this flag before? I was not able to find a usage of the fkag in the referenced commits :-)

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/setup/setupUpgrade.js#L340

пт, 8 июн. 2018 г., 11:18 Ingo Fischer <notifications@github.com>:

**Comment by AlCalzone** [comment]
I see. This affects upgrades, but not fresh installs. Got it.

**Comment by AlCalzone** [comment]
Most of this has been fixed with #99.
We should test which permissions (especially with setcap) need to be set and if we're missing any group memberships
